DROP TABLE IF EXISTS RELAY;

CREATE TABLE RELAY (
       ID INT NOT NULL AUTO_INCREMENT
     , VERSION INT NOT NULL DEFAULT 0
     , SERIAL_NUMBER INT NOT NULL
     , TYPE_ID VARCHAR(10) NOT NULL
     , SHELVE_POSITION INT
     , SERVICE_DATE DATE
     , NEXT_SERVICE_DATE DATE
     , MANUFACTURE_DATE DATE
     , RESPONSIBLE_PERSON VARCHAR(40) NOT NULL
     , UNIQUE UQ_RELAY_1 (SERIAL_NUMBER, TYPE_ID)
     , PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS STATION;

CREATE TABLE STATION (
       ID INT NOT NULL AUTO_INCREMENT
     , VERSION INT NOT NULL DEFAULT 0
     , SERIAL_NUMBER INT NOT NULL
     , TYPE_ID VARCHAR(10) NOT NULL
     , SHELVE_POSITION INT
     , SERVICE_DATE DATE
     , NEXT_SERVICE_DATE DATE
     , MANUFACTURE_DATE DATE
     , RESPONSIBLE_PERSON VARCHAR(40) NOT NULL
     , UNIQUE UQ_RELAY_1 (SERIAL_NUMBER, TYPE_ID)
     , PRIMARY KEY (ID)
);