DROP TABLE IF EXISTS RELAY;
DROP TABLE IF EXISTS STATIV;
DROP TABLE IF EXISTS STATION;

CREATE TABLE RELAY (
       ID INT NOT NULL AUTO_INCREMENT
     , VERSION INT NOT NULL DEFAULT 0
     , SERIAL_NUMBER INT NOT NULL
     , TYPE_ID VARCHAR(10) NOT NULL
     , SHELVE_POSITION INT
     , SERVICE_DATE DATE
     , NEXT_SERVICE_DATE DATE
     , MANUFACTURE_DATE DATE
     , RESPONSIBLE_PERSON VARCHAR(40) NOT NULL
     , STATIV_ID INT NOT NULL
     , UNIQUE UQ_RELAY_1 (SERIAL_NUMBER)
     , PRIMARY KEY (ID)
     , CONSTRAINT FK_STATIV_IN_RELE FOREIGN KEY (STATIV_ID)
         REFERENCES STATIV (ID)
);

CREATE TABLE STATIV (
       ID INT NOT NULL AUTO_INCREMENT
     , VERSION INT NOT NULL DEFAULT 0
     , STATION_ID INT NOT NULL
     , PRIMARY KEY (ID)
     , CONSTRAINT FK_STATION_IN_STATIV FOREIGN KEY (STATION_ID)
         REFERENCES STATION (ID)
);



CREATE TABLE STATION (
       ID INT NOT NULL AUTO_INCREMENT
     , VERSION INT NOT NULL DEFAULT 0
     , STATION_NAME VARCHAR(10) NOT NULL
     , STATIV_ID INT NOT NULL
     , PRIMARY KEY (ID)
     , CONSTRAINT FK_STATIV_IN_STATION FOREIGN KEY (STATIV_ID)
         REFERENCES STATIV (ID)
);
