INSERT INTO PUBLIC.STATION (VERSION, STATION_NAME) VALUES (0, 'Березит');
INSERT INTO PUBLIC.STATIV (VERSION, STATION_ID) VALUES (0, 1);
INSERT INTO PUBLIC.RELAY (VERSION, SERIAL_NUMBER, TYPE_ID, SHELVE_POSITION, SERVICE_DATE, NEXT_SERVICE_DATE, MANUFACTURE_DATE, RESPONSIBLE_PERSON, STATIV_ID) VALUES (0, 123, 'NMSH', 11, '2014-07-01', '2015-07-01', '2013-07-01', 'Person',1);


