INSERT INTO PUBLIC.STATION (STATION_NAME) VALUES ('Березит');
INSERT INTO PUBLIC.STATION (STATION_NAME) VALUES ('Монетная');
INSERT INTO PUBLIC.STATIV (STATION_ID, NUM) VALUES (1, 101);
INSERT INTO PUBLIC.STATIV (STATION_ID, NUM) VALUES (1, 102);
INSERT INTO PUBLIC.RELAY (STATIV_ID, SERIAL_NUMBER, TYPE_ID, SHELVE_POSITION, SERVICE_DATE, NEXT_SERVICE_DATE, MANUFACTURE_DATE, RESPONSIBLE_PERSON, ) VALUES (1, 123, 'NMSH', 11, '2014-07-01', '2015-07-01', '2013-07-01', 'Person');


